# Generated by Django 5.2.8 on 2025-12-02 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0002_remove_adminuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
