# Generated by Django 5.2.8 on 2025-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0003_adminuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default='9191919191', max_length=10),
        ),
    ]
