# Generated by Django 5.2.8 on 2025-12-03 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0004_employee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='contacted', max_length=20)),
                ('total_calls', models.IntegerField(default=0)),
                ('last_call_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_added', to='software_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField()),
                ('call_time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField()),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_app.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='software_app.client')),
            ],
            options={
                'ordering': ['-call_date', '-call_time'],
            },
        ),
    ]
