# Generated by Django 5.2.8 on 2025-12-03 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0005_client_clientcalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='added_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='added_by_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientcalllog',
            name='called_by_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientcalllog',
            name='called_by_role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_added', to='software_app.employee'),
        ),
        migrations.AlterField(
            model_name='clientcalllog',
            name='called_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_app.employee'),
        ),
    ]
