# Generated by Django 5.2.8 on 2025-12-03 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0006_client_added_by_name_client_added_by_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('seo', 'SEO Project'), ('development', 'Development Project')], max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreement', models.FileField(blank=True, null=True, upload_to='project_agreements/')),
                ('module_file', models.FileField(blank=True, null=True, upload_to='project_modules/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('created_by_name', models.CharField(max_length=100)),
                ('created_by_role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='software_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_id', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_role', models.CharField(max_length=50)),
                ('employee_designation', models.CharField(max_length=100)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('assigned_by_name', models.CharField(max_length=100)),
                ('assigned_by_role', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='software_app.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='software_app.project')),
            ],
            options={
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
