# Generated by Django 5.2.8 on 2025-12-04 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0007_project_projectassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('project_id_display', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=20)),
                ('employee_id_display', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_role', models.CharField(max_length=50)),
                ('work_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Hours spent on this project', max_digits=4)),
                ('tasks_completed', models.TextField(help_text='What tasks did you complete today?')),
                ('tasks_in_progress', models.TextField(blank=True, help_text='What are you currently working on?', null=True)),
                ('tasks_planned', models.TextField(blank=True, help_text='What do you plan to work on next?', null=True)),
                ('challenges_faced', models.TextField(blank=True, help_text='Any blockers or challenges?', null=True)),
                ('support_needed', models.TextField(blank=True, help_text='Do you need any help or resources?', null=True)),
                ('overall_status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='in_progress', max_length=20)),
                ('additional_notes', models.TextField(blank=True, help_text='Any other important information', null=True)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='work_reports/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='work_reports/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='work_reports/')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='software_app.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='software_app.project')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'unique_together': {('project', 'employee', 'work_date')},
            },
        ),
    ]
