# Generated by Django 5.2.8 on 2025-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0009_holidaymaster_employeeleavebalance_employeesalary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('HD', 'Half Day'), ('L', 'On Leave'), ('H', 'Holiday')], max_length=20),
        ),
    ]
