# Generated by Django 5.2.8 on 2025-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0011_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='casual_days_used',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='sick_days_used',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('combined', 'Combined Leave'), ('unpaid', 'Unpaid Leave')], max_length=20),
        ),
    ]
