# Generated by Django 5.2.8 on 2025-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0012_leaveapplication_casual_days_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='full_days_count',
            field=models.IntegerField(default=0, help_text='Number of full days in leave'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='half_day',
            field=models.BooleanField(default=False, help_text='Is there a half day in this leave'),
        ),
    ]
