# Generated by Django 5.2.8 on 2025-12-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0013_leaveapplication_full_days_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(default='Head Office', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, default=23.351633, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=85.3162779, max_digits=10)),
                ('radius_meters', models.IntegerField(default=30, help_text='Geofence radius in meters')),
                ('office_start_time', models.TimeField(default='09:30:00')),
                ('office_end_time', models.TimeField(default='18:30:00')),
                ('lunch_break_start', models.TimeField(default='14:00:00')),
                ('lunch_break_end', models.TimeField(default='15:00:00')),
                ('late_threshold', models.TimeField(default='10:30:00', help_text='Late if check-in after this time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geofence Configuration',
                'verbose_name_plural': 'Geofence Configurations',
            },
        ),
        migrations.AlterModelOptions(
            name='employeeleavebalance',
            options={'verbose_name': 'Employee Leave Balance', 'verbose_name_plural': 'Employee Leave Balances'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by_role',
        ),
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='last_credited_date',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='casual_days_used',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='full_days_count',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='half_day',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='sick_days_used',
        ),
        migrations.AddField(
            model_name='attendance',
            name='auto_calculated',
            field=models.BooleanField(default=True, help_text='Auto-calculated from punches'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Checked in after 10:30 AM'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_break_minutes',
            field=models.IntegerField(default=0, help_text='Total break time in minutes'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_work_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total working hours (excluding breaks)', max_digits=4),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='current_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='casual_days_deducted',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='casual_days_requested',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Casual days to be used (for combined leave)', max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='days_actually_taken',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Actual days taken (if returned early)', max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='sick_days_deducted',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='sick_days_requested',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Sick days to be used (for combined leave)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present (P)'), ('absent', 'Absent (A)'), ('half_day', 'Half Day (HD)'), ('on_leave', 'On Leave (L)'), ('holiday', 'Holiday (H)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='casual_leave_balance',
            field=models.DecimalField(decimal_places=1, default=12.0, help_text='Total casual leaves available (12 per year)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=1, default=6.0, help_text='Total sick leaves available (6 per year)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='hr_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('combined', 'Combined Leave (Casual + Sick)'), ('unpaid', 'Unpaid Leave')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('employee_id_display', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('punch_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End')], max_length=15)),
                ('punch_datetime', models.DateTimeField(auto_now_add=True)),
                ('punch_date', models.DateField(auto_now_add=True)),
                ('punch_time', models.TimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Punch location latitude', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Punch location longitude', max_digits=10)),
                ('is_within_geofence', models.BooleanField(default=False, help_text='Is punch within 30m radius?')),
                ('distance_from_office', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in meters', max_digits=6, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='software_app.employee')),
            ],
            options={
                'ordering': ['-punch_datetime'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_attendance', to='software_app.attendancepunch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_attendance', to='software_app.attendancepunch'),
        ),
        migrations.CreateModel(
            name='BreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('attendance_date', models.DateField()),
                ('duration_minutes', models.IntegerField(default=0, help_text='Break duration in minutes')),
                ('is_lunch_break', models.BooleanField(default=False, help_text='Is this the lunch break (2-3 PM)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('break_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='break_ends', to='software_app.attendancepunch')),
                ('break_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_starts', to='software_app.attendancepunch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='software_app.employee')),
            ],
        ),
    ]
