# Generated by Django 5.2.8 on 2025-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0014_geofenceconfig_alter_employeeleavebalance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofenceconfig',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=85.313703, max_digits=10),
        ),
    ]
