# Generated by Django 5.2.8 on 2025-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0015_alter_geofenceconfig_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofenceconfig',
            name='radius_meters',
            field=models.IntegerField(default=70, help_text='Geofence radius in meters'),
        ),
    ]
