# Generated by Django 5.2.8 on 2025-12-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0016_alter_geofenceconfig_radius_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofenceconfig',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=85.3162779, max_digits=10),
        ),
    ]
