# Generated by Django 5.2.8 on 2025-12-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0017_alter_geofenceconfig_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='casual_leave_balance',
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='casual_leaves_taken_this_month',
            field=models.IntegerField(default=0, help_text='Casual leaves used in current month'),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='current_month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='unpaid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=1, default=6.0, help_text='Total sick leaves for the year (6 max)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='casual_days_deducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='casual_days_requested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='days_actually_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('combined', 'Combined Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='sick_days_deducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='sick_days_requested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='total_days',
            field=models.IntegerField(help_text='Total working days requested'),
        ),
    ]
