# Generated by Django 5.2.8 on 2025-12-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0018_remove_employeeleavebalance_casual_leave_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('approved_by_name', models.CharField(max_length=100)),
                ('approved_by_role', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('total_employees', models.IntegerField(help_text='Total active employees in this month')),
                ('total_present_days', models.IntegerField(default=0)),
                ('total_absent_days', models.IntegerField(default=0)),
                ('total_half_days', models.IntegerField(default=0)),
                ('total_leaves', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('locked', 'Locked')], default='approved', max_length=20)),
                ('salary_generated', models.BooleanField(default=False)),
                ('salary_generation_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals', to='software_app.employee')),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals', to='software_app.adminuser')),
            ],
            options={
                'verbose_name': 'Monthly Attendance Approval',
                'verbose_name_plural': 'Monthly Attendance Approvals',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
