# Generated by Django 5.2.8 on 2025-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0019_monthlyattendanceapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryslip',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='leave_encashment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
