# Generated by Django 5.2.8 on 2025-12-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0020_alter_salaryslip_leave_deduction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyattendanceapproval',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyattendanceapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='monthlyattendanceapproval',
            name='approved_by_admin',
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
        migrations.DeleteModel(
            name='MonthlyAttendanceApproval',
        ),
    ]
