# Generated by Django 5.2.8 on 2025-12-10 10:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0021_alter_monthlyattendanceapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default='', help_text='Monthly base salary (will be divided by 30 for per-day calculation)', max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_from', models.DateField(help_text='Salary effective from this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to='software_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('employee_id_display', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Monthly base salary', max_digits=10)),
                ('total_working_days', models.IntegerField(help_text='Total working days in month')),
                ('present_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('absent_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('paid_leaves', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('unpaid_leaves', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('holidays', models.IntegerField(default=0)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('esi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('generated_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_salaries', to='software_app.employee')),
            ],
            options={
                'ordering': ['-year', '-month', 'employee_name'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('approved_by_name', models.CharField(max_length=100)),
                ('approved_by_role', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('total_employees', models.IntegerField(help_text='Total active employees in this month')),
                ('total_present_days', models.IntegerField(default=0)),
                ('total_absent_days', models.IntegerField(default=0)),
                ('total_half_days', models.IntegerField(default=0)),
                ('total_leaves', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('locked', 'Locked')], default='approved', max_length=20)),
                ('salary_generated', models.BooleanField(default=False)),
                ('salary_generation_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals', to='software_app.employee')),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals', to='software_app.adminuser')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
