# Generated by Django 5.2.8 on 2025-12-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0022_employeesalary_compliancesalary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary', max_digits=10),
        ),
        migrations.CreateModel(
            name='EmployeeSalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('employee_id_display', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Monthly travel allowance', max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Monthly food allowance', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to='software_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('employee_id_display', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_role', models.CharField(max_length=50)),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('total_working_days', models.IntegerField(default=0, help_text='Total working days in month (excluding Sundays + holidays)')),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('total_half_days', models.IntegerField(default=0)),
                ('total_leaves', models.IntegerField(default=0)),
                ('total_holidays', models.IntegerField(default=0)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Monthly base salary', max_digits=10)),
                ('per_day_salary', models.DecimalField(decimal_places=2, help_text='Base salary / working days', max_digits=10)),
                ('earned_salary', models.DecimalField(decimal_places=2, default=0, help_text='Calculated: (Present * per_day) + (Half_days * per_day/2) + (Leaves * per_day)', max_digits=10)),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, help_text='One-time bonus for this month', max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, help_text='Any other allowances', max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, help_text='Advance salary already paid', max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Any other deductions (fines, etc.)', max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance from last month (+ve = pending, -ve = extra paid)', max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Earned + Travel + Food + Bonus + Other', max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, help_text='Advance + Other deductions', max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, help_text='Gross - Deductions + Previous Balance', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid till now', max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Net Payable - Total Paid (carries to next month)', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Fully Paid'), ('partially_paid', 'Partially Paid')], default='draft', max_length=20)),
                ('generated_by_name', models.CharField(max_length=100)),
                ('generated_by_role', models.CharField(max_length=50)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to='software_app.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank ref/Cheque no/UPI ID', max_length=100, null=True)),
                ('paid_by_name', models.CharField(max_length=100)),
                ('paid_by_role', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='software_app.monthlysalary')),
            ],
        ),
        migrations.DeleteModel(
            name='ComplianceSalary',
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
        migrations.DeleteModel(
            name='SalarySlip',
        ),
    ]
