# Generated by Django 5.2.8 on 2025-12-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0023_remove_employeesalary_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypayment',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='advance_paid',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='approved_by_name',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='approved_by_role',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='earned_salary',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='employee_role',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='food_allowance',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='generated_by_name',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='generated_by_role',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='generated_date',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='other_allowances',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='status',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='total_holidays',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='total_working_days',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='esi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='esi_percent',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='is_saved',
            field=models.BooleanField(default=False, help_text='Data saved permanently'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='pf_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='pf_percent',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryConfig',
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
