# Generated by Django 5.2.8 on 2025-12-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0024_remove_salarypayment_monthly_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('old_status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('holiday', 'Holiday')], max_length=20)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('holiday', 'Holiday')], max_length=20)),
                ('reason', models.TextField()),
                ('changed_by_name', models.CharField(max_length=200)),
                ('changed_by_role', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='software_app.attendance')),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_changes_made', to='software_app.adminuser')),
                ('changed_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_changes_made', to='software_app.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_status_changes', to='software_app.employee')),
            ],
            options={
                'verbose_name': 'Attendance Status Change Log',
                'verbose_name_plural': 'Attendance Status Change Logs',
                'db_table': 'attendance_status_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
