# Generated by Django 5.2.8 on 2025-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0025_attendancestatuschangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendanceapproval',
            name='approved_up_to_date',
            field=models.DateField(blank=True, help_text='Date up to which attendance was approved', null=True),
        ),
    ]
