# Generated by Django 5.2.8 on 2025-12-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0026_monthlyattendanceapproval_approved_up_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin')], default='super_admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('sales', 'Sales'), ('developer', 'Developer'), ('seos', 'Seos')], max_length=20),
        ),
    ]
