# Generated by Django 5.2.8 on 2025-12-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0027_employee_account_holder_name_employee_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofenceconfig',
            name='radius_meters',
            field=models.IntegerField(default=80, help_text='Geofence radius in meters'),
        ),
    ]
