# Generated by Django 5.2.8 on 2025-12-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0028_alter_geofenceconfig_radius_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('assigned_to_id_display', models.CharField(max_length=10)),
                ('assigned_to_name', models.CharField(max_length=100)),
                ('assigned_to_role', models.CharField(max_length=50)),
                ('task_title', models.CharField(help_text='Short task title', max_length=200)),
                ('task_description', models.TextField(help_text='Detailed task description')),
                ('task_file', models.FileField(blank=True, help_text='Reference file', null=True, upload_to='task_files/')),
                ('due_date', models.DateField(help_text='Task deadline date')),
                ('due_time', models.TimeField(help_text='Task deadline time')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(blank=True, help_text='When employee accepted', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='When employee completed', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text="Employee's completion report", null=True)),
                ('time_taken_minutes', models.IntegerField(default=0, help_text='Time from accept to complete')),
                ('assigned_by_name', models.CharField(max_length=100)),
                ('assigned_by_role', models.CharField(default='super_admin', max_length=50)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='software_app.adminuser')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='software_app.employee')),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_completion_files/')),
                ('file_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_files', to='software_app.taskassignment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
