# Generated by Django 5.2.8 on 2025-12-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0029_taskassignment_taskcompletionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_employees', to='software_app.adminuser'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
