# Generated by Django 5.2.8 on 2025-12-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0030_employee_blocked_at_employee_blocked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_received_from_clients', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_as_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Company Funds',
                'verbose_name_plural': 'Company Funds',
            },
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='payment_from_funds',
            field=models.BooleanField(default=False, help_text='Was this salary paid from company funds?'),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_pending',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount to be received', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount received from client', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total project value in INR', max_digits=10),
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('initial_deposit', 'Initial Deposit'), ('client_payment', 'Client Payment'), ('salary_payment', 'Salary Payment'), ('adjustment', 'Manual Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_credit', models.BooleanField(help_text='True = Money IN, False = Money OUT')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField()),
                ('created_by_name', models.CharField(max_length=100)),
                ('created_by_role', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_app.adminuser')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to='software_app.project')),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to='software_app.monthlysalary')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='fund_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='software_app.fundtransaction'),
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recorded_by_name', models.CharField(max_length=100)),
                ('recorded_by_role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_app.fundtransaction')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='software_app.project')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
