# Generated by Django 5.2.8 on 2025-12-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0031_companyfunds_monthlysalary_payment_from_funds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('sales', 'Sales'), ('developer', 'Developer'), ('seos', 'Seos'), ('digital_marketing', 'Digital Marketing')], max_length=20),
        ),
    ]
