# Generated by Django 5.2.8 on 2025-12-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0032_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(help_text='Kisliye kharcha hua? (Pantry, Electricity, etc.)')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('company_card', 'Company Card')], default='cash', max_length=30)),
                ('added_by_name', models.CharField(max_length=100)),
                ('added_by_role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_app.fundtransaction')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
