# Generated by Django 5.2.8 on 2025-12-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0033_companyexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present (P)'), ('absent', 'Absent (A)'), ('half_day', 'Half Day (HD)'), ('on_leave', 'On Leave (L)'), ('holiday', 'Holiday (H)'), ('lwp', 'Leave Without Pay (LWP)'), ('ncnp', 'No Call No Present (NCNP)')], max_length=20),
        ),
    ]
