# Generated by Django 5.2.8 on 2026-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0034_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_in_training',
            field=models.BooleanField(default=True, help_text='First 7 days = Training period'),
        ),
        migrations.AddField(
            model_name='employee',
            name='training_per_day_salary',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Daily salary during training (₹100)', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='training_start_date',
            field=models.DateField(blank=True, help_text='Date when employee joined (for 7-day training calculation)', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present (P)'), ('absent', 'Absent (A)'), ('half_day', 'Half Day (HD)'), ('on_leave', 'On Leave (L)'), ('holiday', 'Holiday (H)'), ('lwp', 'Leave Without Pay (LWP)'), ('ncnp', 'No Call No Present (NCNP)'), ('training', 'Training (T)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='current_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='current_year',
            field=models.IntegerField(default=2026),
        ),
    ]
