# Generated by Django 5.2.8 on 2026-01-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0035_employee_is_in_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatuschangelog',
            name='new_status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('lwp', 'Leave Without Pay'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancestatuschangelog',
            name='old_status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('lwp', 'Leave Without Pay'), ('training', 'Training')], max_length=20),
        ),
    ]
