# Generated by Django 5.2.8 on 2026-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0036_alter_attendancestatuschangelog_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_in_training',
            field=models.BooleanField(default=True, help_text='First 7 ACTUAL training days (excluding holidays/absents)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='training_start_date',
            field=models.DateField(blank=True, help_text='Date when employee joined', null=True),
        ),
    ]
