# Generated by Django 5.2.8 on 2026-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0037_alter_employee_is_in_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
