# Generated by Django 5.2.8 on 2026-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0039_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_in_training',
            field=models.BooleanField(default=False, help_text='First 7 ACTUAL training days (excluding holidays/absents)'),
        ),
    ]
