# Generated by Django 5.2.8 on 2026-01-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_app', '0040_alter_employee_is_in_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
